Note that this repo is now deprecated
UKHomeOffice/hof pull request #191
Opened 2017-05-04 14:02 UTC by timgent

Update readme to say this repo is deprecated

2017-05-04 14:05 UTC, lennym requested changes

2017-05-04 14:05 UTC, lennym commented on README.md
> +Please refer to the [new HOF repo](https://github.com/UKHomeOfficeForms/hof)
Thanks. One small thing: that link should point to https://github.com/UKHomeOfficeForms/hof-bootstrap

2017-05-04 14:05 UTC, JoeChapman commented
I think we need to talk about what the link should point to. I might make more sense to point at the Github Page (getting started doc)

2017-05-19 15:35 UTC, lennym commented
This was merged as part of #192 - closing.

2017-05-19 15:35 UTC, closed without merging